# Generated by Django 4.1.1 on 2022-09-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("number", models.IntegerField()),
                ("about", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
                ("register_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateField(auto_now=True)),
                ("slug", models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
