# Generated by Django 4.1.1 on 2022-09-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fscohort", "0003_category_review_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Student", "verbose_name_plural": "Students"},
        ),
        migrations.RemoveField(model_name="review", name="categories",),
        migrations.AddField(
            model_name="student",
            name="categories",
            field=models.ManyToManyField(
                related_name="students", to="fscohort.category"
            ),
        ),
    ]
