# Generated by Django 4.1.1 on 2022-09-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fscohort", "0004_alter_student_options_remove_review_categories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="product_img",
            field=models.ImageField(
                blank=True,
                default="defaults/clarusway.png",
                null=True,
                upload_to="product/",
            ),
        ),
    ]
