# Generated by Django 4.1.1 on 2022-09-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fscohort", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
    ]
